**Create a vector (array) of 1XN dimension representing N-
dimensional feature vector of a sample. Write a program to
compute the mean and variance of the elements present in the
array.**

In [5]:
import numpy as np

N = 10

array = np.random.rand(N)
mean = np.mean(array)

# Calculating variance using inbuilt function
variance = np.var(array)
print(f"Array: {array}")
print(f"Mean: {mean}")
print(f"Variance: {variance}")


# Calculating variance manually
v = sum((xi - mean) ** 2 for xi in array) / N
print(v)

Array: [0.8729557  0.82348192 0.00973007 0.5973235  0.68578075 0.18855425
 0.90434428 0.39577165 0.69908683 0.44447764]
Mean: 0.5621506596756818
Variance: 0.08035350182287501
0.08035350182287501


**Create two vectors each of dimension 1XM each representing N-dimensional feature vector of a sample. Write a program to compute the Covariance between them**

In [9]:
import numpy as np
M = 10
X = np.random.rand(M)
Y = np.random.rand(M)
mean_X = np.mean(X)
mean_Y = np.mean(Y)

# Calculate covariance manually
covariance = sum((X[i] - mean_X) * (Y[i] - mean_Y) for i in range(M)) / M
print(f"Vector X: {X}")
print(f"Vector Y: {Y}")
print(f"Mean of Vector X: {mean_X}")
print(f"Mean of Vector Y: {mean_Y}")
print(f"Covariance: {covariance}")

# Calculate covariance using inbuilt function
covariance_matrix = np.cov(X, Y, ddof=0)
covx = covariance_matrix[0, 1]
print(covx)


Vector X: [0.20728054 0.31062779 0.93661996 0.15628231 0.94443099 0.09648614
 0.74653493 0.63621664 0.06921235 0.2655974 ]
Vector Y: [0.3595398  0.06249299 0.19657154 0.28599933 0.54972103 0.23824417
 0.96548648 0.86671863 0.92212632 0.05763952]
Mean of Vector X: 0.4369289067564006
Mean of Vector Y: 0.4504539805298597
Covariance: 0.024806595182602996
0.024806595182603


**Create two vectors each of dimension 1XN. Write a program to
compute the Correlation between them.**

In [11]:
import numpy as np
N = 10
X = np.random.rand(N)
Y = np.random.rand(N)
correlation_matrix = np.corrcoef(X, Y, ddof=0)

# Extracting the correlation value
correlation = correlation_matrix[0, 1]
print(f"Vector X: {X}")
print(f"Vector Y: {Y}")
print(f"Correlation: {correlation}")


Vector X: [0.34526451 0.57896922 0.54966533 0.00147465 0.10017747 0.49909816
 0.64698244 0.10005508 0.04542018 0.81759447]
Vector Y: [0.12195249 0.7186607  0.02881136 0.53556823 0.66242141 0.62751573
 0.13770912 0.45471851 0.37836266 0.6311779 ]
Correlation: -0.09278431268385326


<ipython-input-11-79593cfce575>:5: DeprecationWarning: bias and ddof have no effect and are deprecated
  correlation_matrix = np.corrcoef(X, Y, ddof=0)


**Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i.e. (i,j)th entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and correlation matrix. Comment on takeaways from these matrixes.**

In [12]:
import numpy as np

# Number of features
M = 4
# Number of samples
N = 10

matrix = np.random.rand(M, N)
covariance_matrix = np.cov(matrix, rowvar=True, bias=True)
correlation_matrix = np.corrcoef(matrix)
print("Matrix (M x N):")
print(matrix)
print("\nCovariance Matrix:")
print(covariance_matrix)
print("\nCorrelation Matrix:")
print(correlation_matrix)


Matrix (M x N):
[[0.07729985 0.07112803 0.76876449 0.74396861 0.88670326 0.31269586
  0.39949291 0.90603006 0.40130098 0.53544034]
 [0.9795206  0.50376851 0.16976271 0.17546991 0.16920936 0.05687236
  0.2906726  0.53152759 0.82295436 0.33840413]
 [0.42890329 0.21922583 0.65668699 0.26878388 0.0702294  0.09505958
  0.22346594 0.71041262 0.36810615 0.79600907]
 [0.99854207 0.88221396 0.30839351 0.18897282 0.89882287 0.36146964
  0.38722519 0.52299528 0.57823803 0.05024114]]

Covariance Matrix:
[[ 0.08638862 -0.04110312  0.01945201 -0.03266705]
 [-0.04110312  0.08328267  0.0171964   0.04734885]
 [ 0.01945201  0.0171964   0.06010578 -0.03030008]
 [-0.03266705  0.04734885 -0.03030008  0.09248472]]

Correlation Matrix:
[[ 1.         -0.48458421  0.26994679 -0.36546572]
 [-0.48458421  1.          0.24305368  0.53950704]
 [ 0.26994679  0.24305368  1.         -0.40639715]
 [-0.36546572  0.53950704 -0.40639715  1.        ]]
